#!/bin/bash
# select a random movie from the ~/Movies folder
# can also be just ls /media/TVShows | shuf -n 1 but fuck it....

files=$(find /media/TVShows \( ! -regex '.*/\..*' \) -type f 2>/dev/null | tr -s ' ' '::')
file_matrix=($files)
num_files=${#file_matrix[*]}
echo ""
echo "${file_matrix[$((RANDOM%num_files))]}" | tr -s '::' ' ' | xargs -n1 -0 basename
exit 0

